COPY_TO_SERVER=1;
COPY_TO_LOCAL=2;
DELETE_SERVER=3;
DELETE_LOCAL=4;

ACTIONS[$COPY_TO_SERVER]="COPY_TO_SERVER";
ACTIONS[$COPY_TO_LOCAL]="COPY_TO_LOCAL";
ACTIONS[$DELETE_SERVER]="DELETE_SERVER";
ACTIONS[$DELETE_LOCAL]="DELETE_LOCAL";
